pdfjs.upgrade.error=Unable to display this PDF.
pdfjs.upgrade.download=Download the file to view it locally.
pdfjs.upgrade.unsupportedBrowser=This PDF viewer requires a modern browser such as Chrome, Edge, Firefox or Safari.
